### ISSUE TITLE
lib is ignoring initial "colorMode/preference" and switches to "system"

### ISSUE THREAD

**Issue by piotrku** [nuxt-modules/color-mode#114]
### Version
@nuxtjs/color-mode: 2.1.11
nuxt: 2.15.7

is there any reason for the lib to automatically switch always to 'system' preferences although non regarding the initial config in `nuxt.config.js`?
```
colorMode: {
    preference: 'light', // default value of $colorMode.preference
    fallback: 'light', // fallback value if not system preference found
    classSuffix: "", // removing -mode suffix for Tailwind Dark mode support
    hid: 'nuxt-color-mode-script',
    storageKey: 'nuxt-color-mode'
  },
```

I check this on main component mounted:
```
    console.log('value:', this.$colorMode.value);
    console.log('forced:', this.$colorMode.forced);
    console.log('preference:', this.$colorMode.preference);

    setTimeout(() => {
      console.log('value:', this.$colorMode.value);
      console.log('forced:', this.$colorMode.forced);
      console.log('preference:', this.$colorMode.preference);
    }, 10);
```

and the result is:

![image](https://user-images.githubusercontent.com/3919799/145991468-5119a694-3aee-4ad2-a4f7-0a66fbd9e627.png)

I expect it to stay in my initial 'light' mode - instead of switching to system's dark

**Comment by jillztom** [comment]
Is there any update on this?

**Comment by TJacoob** [comment]
I'm having the same issue using Nuxt3.

**Comment by sunupf** [comment]
I have similar issue, but when I re-arrange the module order it's fix it,

this not work
```
modules: [
    '@nuxthq/ui',
    '@nuxtjs/color-mode',
    '@nuxtjs/i18n',
  ],
```

this work
```
modules: [
    '@nuxtjs/color-mode',
    '@nuxthq/ui',
    '@nuxtjs/i18n',
  ],
```

**Comment by antfu** [comment]
Close as this has been stable for a long while. If you still face a similar issue with the latest module on Nuxt 3, open a new issue with minimal reproductions. Thanks.

**Comment by bayramorhan** [comment]
In your app.vue, add this code to force the color mode

```
<script setup>
const colorMode = useColorMode();

onMounted(async () => {
  await nextTick();
  colorMode.preference = "light";  // or dark
});
</script>
```

**Comment by tkzt** [comment]
Same situation encountered. Finally found that: **forgetting to reset the relevant local storage item**.
