### ISSUE TITLE
Cannot read properties of undefined (reading 'colorMode')

### ISSUE THREAD

**Issue by Luferov** [nuxt-modules/color-mode#158]
### Version
@nuxtjs/color-mode:  ^3.1.4
nuxt-bridge: 

### Reproduction Link
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/26242554/188740767-034d906a-e371-4676-9ea5-8ba29c09cab4.png">### What is Expected?

### What is actually happening?

When ssr server crashes with an error

**Comment by Luferov** [comment]
When options?.colorMode - works good!

**Comment by Luferov** [comment]
Sometimes work smonetimes no :\
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/26242554/188744917-e91b1bf2-b1b2-45fe-8d9c-38c46dcbf22c.png">

**Comment by Luferov** [comment]
I found a pattern. This happens when using

const router = useRouter()
router.push(...)

**Comment by danielroe** [comment]
Do you have a reproduction?
