### ISSUE TITLE
bug(types): `ColorScheme` component

### ISSUE THREAD

**Issue by Lexpeartha** [nuxt-modules/color-mode#168]
### Version
@nuxtjs/color-mode: v3.1.8
nuxt: v3.0.0-rc.11

### Reproduction Link
Not sure how to actually reproduce

![image](https://user-images.githubusercontent.com/43365376/194695576-0b12ae76-2376-4b7c-8049-71cc1ecb102a.png)

Replacing this with just `ClientOnly` doesn't throw any type error

**Comment by Lexpeartha** [comment]
It might help migrating the component to TS type inferring for props and script setup syntax?

**Comment by Atinux** [comment]
I would love some help yes @Lexpeartha

**Comment by danielroe** [comment]
Do you still experience this? This is not reproducible for me.

![CleanShot 2024-04-25 at 23 59 02@2x](https://github.com/nuxt-modules/color-mode/assets/28706372/a3150a41-d1ee-4cef-81b9-7e968edbbb36)

Let me know if so and I'll happily reopen.
