### ISSUE TITLE
Missing current instance. useRouter() must be called inside <script setup> or setup()

### ISSUE THREAD

**Issue by Luferov** [nuxt-modules/color-mode#169]
### Version
@nuxtjs/color-mode: 3.1.8
Nuxi 3.0.0-rc.11
Nuxt 2.16.0-27720022.54e852f with Nitro 0.5.4

### What is Expected?

When using nuht/bridge with nuxt-rc.11, an error appears.
![image](https://user-images.githubusercontent.com/26242554/194948924-069f9f00-f805-4e61-ad9b-32e17bd09ea9.png)

![image](https://user-images.githubusercontent.com/26242554/194949045-09061244-8bc5-4d81-8ea0-e751c51b83d3.png)

**Comment by P4sca1** [comment]
https://github.com/nuxt/bridge/issues/554

**Comment by P4sca1** [comment]
Using `useRouter()` should work fine. This is an issue with Nuxt Bridge that got introduced in https://github.com/nuxt/bridge/pull/533 (see the issue I linked).

**Comment by Luferov** [comment]
> Using `useRouter()` should work fine. This is an issue with Nuxt Bridge that got introduced in [nuxt/bridge#533](https://github.com/nuxt/bridge/pull/533) (see the issue I linked).

Yep, but it doesn’t work. In nuxt/bridge#533 deleted  useRoute, and this I added solution through nuxtApp.

**Comment by P4sca1** [comment]
We should probably fix the upstream issue instead of adding a workaround in all modules where useRouter is used.

**Comment by Luferov** [comment]
I agree, however this fix allows the system to work now.

**Comment by Luferov** [comment]
@P4sca1 when this problem will resolve global, what do you thins about this?

**Comment by P4sca1** [comment]
I don't know when the issue gets resolved. Maybe @danielroe can tell. But I think Nuxt 3 issues have priority before Nuxt Bridge issues at the moment.

**Comment by danielroe** [comment]
Yes, I think we should fix this in bridge.

**Comment by Luferov** [comment]
It would be great! ❤️

**Comment by NtchPlayer** [comment]
Hi !
Any news about this issue ? I see RC 12 of Nuxt 3 is now available, I don't know the delay between a new RC of Nuxt 3 and a new release of Nuxt Bridge 🤔

**Comment by Luferov** [comment]
@danielroe look like revert or no?

**Comment by Luferov** [comment]
> Can you confirm the bug is fixed with latest bridge?

Works good!
