### ISSUE TITLE
It doesn't work with nuxt 3.0.0-rc.10

### ISSUE THREAD

**Issue by RajinCoding2007** [nuxt-modules/color-mode#171]
### Version
@nuxtjs/color-mode: 3.0.0
nuxt: 3.0.0-rc.10

### Reproduction Link

[https://stackblitz.com/edit/nuxt-color-mode-shpm1b](https://stackblitz.com/edit/nuxt-color-mode-shpm1b)
### Steps to reproduce
I just opened the demo of Nuxt color mode in Stackblitz and then changed the `package.json` and `nuxt.config.ts` . Now it doesn't work.

### What is Expected?
I expected that icons will be shown

### What is actually happening?
But icons are not being shown.

**Comment by priverop** [comment]
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/1587633/207660935-850f85ac-fad6-4cd0-9dfe-cc77786d7e4d.png">

I can see the icons and everything is working. @RajinCoding2007 is that link correct?
