### ISSUE TITLE
nuxt kit not up to date, cannot auto import `useColorMode()`

### ISSUE THREAD

**Issue by huang-julien** [nuxt-modules/color-mode#175]
### Version
@nuxtjs/color-mode: 3.1.8 
nuxt: 3.0.0

### Steps to reproduce

Try to autoimport `useColorMode` in any composable or component

### What is Expected?

It should be imported

### What is actually happening?

IDE warns that it is not defined. And a page calling `useColorMode` will throw an error

### Why

in @nuxt/kit rc9, it adds autoimport using `autoImports:extend` which is deprecated

Can this be exported by the package ? We would be able to import it manually using 
`import { useColorMode } from "@nuxtjs/color-mode"`

**Comment by dargmuesli** [comment]
@Atinux https://github.com/nuxt-modules/color-mode/pull/161 would resolve this issue

**Comment by danielroe** [comment]
give it a go with v3.2.0 and let me know if it's resolved for you.

**Comment by huang-julien** [comment]
solved with 3.2.0 ❤️
