### ISSUE TITLE
cookies and localstorage as options

### ISSUE THREAD

**Issue by tasiotas** [nuxt-modules/color-mode#186]
Hi,

Currently this module is using localstorage to save user preference. That's cool, but we cannot use it across subdomains.

Could you please add cookies as alternative storage solution that works across subdomains?

Thank you

**Comment by Hossein-Mirazimi** [comment]
> Hi,
> 
> Currently this module is using localstorage to save user preference. That's cool, but we cannot use it across subdomains.
> 
> Could you please add cookies as alternative storage solution that works across subdomains?
> 
> Thank you

Hi
I try to add options for sync location storage with cookie
I think this change will resolve this issue
#188

**Comment by abdonrd** [comment]
Any progress with this?

**Comment by tasiotas** [comment]
latest version implements this feature. Sadly no control over cookie `path`, `domain` etc
