### ISSUE TITLE
Throws Error about accessing `preference` of `undefined`

### ISSUE THREAD

**Issue by chrisspiegl** [nuxt-modules/color-mode#212]
### Version

See Reproduction

### Reproduction Link

https://codesandbox.io/p/sandbox/reproduction-color-mode-preference-of-undefined-mp9252?file=%2Fpackage.json%3A5%2C22

### Steps to reproduce

Running Vitest in a Package that uses `@nuxtjs/color-mode` throws error upon initialization.

It is enough to have `@nuxtjs/color-mode` in the `nuxt.config.js` file without accessing the `useColorMode()` anywhere in code.

Running `pnpm vitest` in the reproduction throws:

```
[nuxt] error caught during app initialization TypeError: Cannot read properties of undefined (reading 'preference')
```

### What is Expected?

Vitest should run without throwing any error.

### What is actually happening?

Running Vitest throws an error as described above when `@nuxtjs/color-mode` is present as a module in `nuxt.config.js`.

**Comment by Extarys** [comment]
Came up with this error today, I disabled the module for now.

**Comment by oluwakayode-a** [comment]
Ran into this issue today with Nuxt 3.8; seems the last working version is Nuxt 3.6

**Comment by l4dybird** [comment]
In my environment, v3.3.1 resolved the issue.

**Comment by chrisspiegl** [comment]
I now also ran my code with vitest and the latest versions of both `@nuxt/test-utils`, `vitest`, and `@nuxtjs/color-mode` at `3.3.2`.
