### ISSUE TITLE
Question about demo asset regarding license

### ISSUE THREAD

**Issue by mario-nt** [nuxt-modules/color-mode#233]
Hi!

I want to use the three icons used in the demo (System, light and dark SVG icon) for a project:

![image](https://github.com/nuxt-modules/color-mode/assets/141633147/00e20eee-1882-4743-9261-4457ba05dddb)

I want to ask if they are included in the MIT license, as far as I understand it, they are under the MIT license that applies to the project, but wanted to double check it.

Thank you in advance.

**Comment by dungsil** [comment]
This icon looks like part of the feather project

 - https://feathericons.com/?query=monitor
 - https://feathericons.com/?query=sun
 - https://feathericons.com/?query=moon

**Comment by mario-nt** [comment]
> This icon looks like part of the feather project
> 
>     * https://feathericons.com/?query=monitor
> 
>     * https://feathericons.com/?query=sun
> 
>     * https://feathericons.com/?query=moon
> 
> 
> The feather project is licensed under [MIT](https://github.com/feathericons/feather/blob/main/LICENSE), so I think you can use it.

Hi @dungsil, yup, It seems like is part of the feather project, and it has a MIT license.

Thank you so much for your answer :)
