### ISSUE TITLE
TypeError: Mt.getColorScheme

### ISSUE THREAD

**Issue by moshetanzer** [nuxt-modules/color-mode#267]
### Version
@nuxtjs/color-mode: 
nuxt: 

### Steps to reproduce

Nuxt (latest), Nuxt UI Pro (latest)

### What is Expected?

Page to work.

### What is actually happening?

As soon as page is hydrated it shows a 404 error in production only.

[nuxt] error caught during app initialization TypeError: Mt.getColorScheme is not a function
    at w6iphiSl.js:39:757
    at w6iphiSl.js:24:20608
    at Object.runWithContext (w6iphiSl.js:14:19608)
    at O (w6iphiSl.js:24:19728)
    at w6iphiSl.js:24:20602
    at Array.forEach (<anonymous>)
    at N (w6iphiSl.js:24:20591)
    at w6iphiSl.js:24:19544
    at async w6iphiSl.js:24:37454
    at async tf (w6iphiSl.js:49:64408)

**Comment by atinux** [comment]
What browser do you use?
