### ISSUE TITLE
TS complains "Object literal may only specify known properties, and 'colorMode' does not exist in type 'InputConfig<NuxtConfig, ConfigLayerMeta>'."

### ISSUE THREAD

**Issue by rowild** [nuxt-modules/color-mode#273]
### Version
@nuxtjs/color-mode: 3.4.2
nuxt: 3.12.3

### Steps to reproduce
1. Setup a new Nuxt project with `npx nuxi@latest init <project-name>`
2. cd <project-name>
3. npm i
4. npm i -D @nuxtjs/color-mode
5. Add to `export default defineNuxtConfig({`

` 
    colorMode: {
      preference: 'system', // default value of $colorMode.preference
      fallback: 'light', // fallback value if not system preference found
      hid: 'nuxt-color-mode-script',
      globalName: '__NUXT_COLOR_MODE__',
      componentName: 'ColorScheme',
      classPrefix: '',
      classSuffix: '-mode',
      storageKey: 'nuxt-color-mode'
    },
`

### What is Expected?
No errors

### What is actually happening?
TypeScript complains and errors are popping up as can be seen in the screenshot

![Screenshot 2024-07-04 at 17 49 05](https://github.com/nuxt-modules/color-mode/assets/213803/bed9f7ae-ee09-4900-b9bd-113d7725772b)

**Comment by reiyanyan** [comment]
just run "npm run postinstall" to re-generate types in `.nuxt/`

**Comment by Liuzhch1** [comment]
I sloved this issue by `pnpm add @nuxtjs/color-mode` package and add it in `nuxt.config.ts`.
```diff
// nuxt.config.ts
export default defineNuxtConfig({
+ modules: ["@nuxtjs/color-mode"],
  colorMode: {
    preference: "light",
  },
  compatibilityDate: "2024-04-03",
  devtools: { enabled: true },
});
```
Hope this works for you

**Comment by humblemodulo** [comment]
> just run "npm run postinstall" to re-generate types in `.nuxt/`

This "fix" doesn't work for me.  My `nuxt.config.ts` includes:

```
modules: [
    '@nuxtjs/mdc',
    '@nuxt/image',
    '@nuxtjs/color-mode',
    '@nuxt/content',
    '@nuxtjs/robots',
    '@formkit/nuxt',
  ],
  
  colorMode: {
    classSuffix: '',
    preference: 'dark',
    fallback: 'light',
  },

  ```

. . .however, no cache/directory clearing or "TS Server Restart" makes any difference.  Warning still occurs.  🤔
